$(() => {
    const $container = $('#container');
    $("body").append($container);
console.log($container);
    const $h1 = $('<h1>').text("Harry");
    $container.append($h1);
console.log($h1);
    const $h2 = $('<h2>').text("Dan");
    $container.append($h2);
console.log($h2);
const $h3 = $('<h3>').text("Hufflepuff");
    $container.append($h3);
console.log($h3);
const $h4 = $('<h4>').text("Billy").addClass("cat");
    $container.append($h4);
console.log($h4);
const $h5 = $('<h4>').text("Hornbeam with Dragon Heartstring Core");
    $container.append($h5);
console.log($h5);
const $items = $('<ul>');
const $ButterBeer = $('<li>').text("Butter Beer");
$items.append($ButterBeer);
const $InvisibilityCloak = $('<li>').text("Invisibility Cloak").addClass("secret");
$items.append($InvisibilityCloak);
const $MagicMap = $('<li>').text("Magic Map").addClass("secret");
$items.append($MagicMap);
const $TimeTurner = $('<li>').text("Time Turner").addClass("secret");
$items.append($TimeTurner);
const $Leash = $('<li>').text("Leash").addClass("cat");
$items.append($Leash);
const $BertiesBeans = $('<li>').text("Bertie\'s Every Flavor Beans");
$items.append($BertiesBeans);
$container.append($items);
console.log($items);
});
